### ISSUE TITLE
Impossible de créer des nouvelles tache ou de nouveaux objectifs

### ISSUE THREAD

**Issue by NHerve** [Jeje2201/ScrumManager#1]
**Décrire le bug**
Impossible de créer des nouvelles tache ou de nouveaux objectifs
![bug_scrum_manager](https://user-images.githubusercontent.com/24428333/51463287-1c94ea80-1d63-11e9-8d49-52728534c60b.png)
![bug_obj_scrum_manager](https://user-images.githubusercontent.com/24428333/51463289-1d2d8100-1d63-11e9-920e-cc1c26333ba6.png)

**Comment by Jeje2201** [comment]
Problème fixé avec ces 2 commits pushé depuis le Narc : 
https://github.com/Jeje2201/ScrumManager/commit/ee70a25d1c17d57b767be52ad452e5166eaab30a
https://github.com/Jeje2201/ScrumManager/commit/33f122b9fcc406ade27c5c001c83779586612144
Pull effectué à l'instant, application à nouveau fonctionnelle pour le moment.
