### ISSUE TITLE
Validation tâche

### ISSUE THREAD

**Issue by Naomi-Fischer** [Jeje2201/ScrumManager#10]
Pour valider les tâches est ce qu'on ne pourrait pas avoir une checkbox ou un bouton, histoire de n'avoir à cliquer qu'une fois sans besoin de remonter pour valider ?

**Comment by Jeje2201** [comment]
Donc genre dès que tu clic dessus, ça la valide directement ?

**Comment by Jeje2201** [comment]
Aucun retour apres 2semaines, et nouvelles maquettes qui vont encore changé le processus de validation, a réouvrir si le probleme persiste apres les prochaines maquettes
