### ISSUE TITLE
Préparation de la planif

### ISSUE THREAD

**Issue by anthonyHenryNS** [Jeje2201/ScrumManager#13]
Une petite interface permettant de préparer sa planif pourrait être sympa, sur le principe du fichier html qui charge les tâches sur lesquels on est sur pivotal et qui permet de sélectionner ce qu'on veux inclure en comptabilisant le nombre d'heures.

Derrière le Scrum master aurait du coup une planif pré-rempli et n'aurait plus qu'à valider !

Planif + simple pour le user et moins longue à saisir pour le Scrum master :)

**Comment by Jeje2201** [comment]
> Derrière le Scrum master aurait du coup une planif pré-rempli et n'aurait plus qu'à valider !

Ce qui fix le problème de "C'est seulement le Scrum Master qui valide"

> Planif + simple pour le user et moins longue à saisir pour le Scrum master :)

Tu le vends vraiment bien 😛 

Je pense m'attaquer dessus pour le prochain sprint du 16 mars !

**Comment by Jeje2201** [comment]
Au final tâche en attente du choix pipefy, trello, ou autre..

**Comment by Jeje2201** [comment]
L'attente est trop longue, codé en une journée
