### ISSUE TITLE
Taille des labels dans interférences

### ISSUE THREAD

**Issue by jvitus** [Jeje2201/ScrumManager#17]
Il faudrait prévoir une taille plus grande pour les labels dans les interférences, je ne sais pas la limite de caractères mais on devrait pouvoir mettre un maximum d'informations. 

Bon et soyons tatillons le back qui retourne un 200 quand le post échoue c'est pas très REST
![bug scrummanger](https://user-images.githubusercontent.com/5540281/77741567-63403d80-7015-11ea-99fd-b49b28fc0930.JPG)
![bug scrummanger2](https://user-images.githubusercontent.com/5540281/77741573-650a0100-7015-11ea-8665-73a0109cb7ca.JPG)

**Comment by Jeje2201** [comment]
Ca devrait être fixé ! 
![image](https://user-images.githubusercontent.com/19387127/77932682-2c388900-72ae-11ea-82cd-03527ad1bb9a.png)
