### ISSUE TITLE
Tâches indescendable

### ISSUE THREAD

**Issue by 20cents** [Jeje2201/ScrumManager#19]
J'ai 2 tâches (du même projet Pivotal) que je n'arrive pas à descendre :
L'app fait une requête (une par tâche) sur l'api Pivotal qui retourne une erreur 403
https://www.pivotaltracker.com/services/v5/projects/2430512/stories/171856185/tasks/69325301
https://www.pivotaltracker.com/services/v5/projects/2430512/stories/171856241/tasks/69325332

Dans les 2 cas le message est le même :
code: "unauthorized_operation"
kind: "error"
error: "Authorization failure."
general_problem: "You aren't authorized to access the requested resource."
possible_fix: "Your project permissions are determined on the Project Membership page. If you are receiving this error you may be trying to access the wrong project, or the project API access is disabled, or someone listed as the project's Owner needs to change your membership type."

**Comment by Jeje2201** [comment]
Fix, problème du token qui était la mien, Fred a renouvelé le sien et je l'ai remplacé
