### ISSUE TITLE
Certaines colonnes n'ont pas de champs 

### ISSUE THREAD

**Issue by NHerve** [Jeje2201/ScrumManager#2]
**Décrire le bug**
Certaines colonnes n'ont pas de champs 
![unnamed](https://user-images.githubusercontent.com/24428333/51463418-772e4680-1d63-11e9-9de9-57b398cdc61e.png)
![unnamed 2](https://user-images.githubusercontent.com/24428333/51463419-772e4680-1d63-11e9-8d0a-d6e10be1b302.png)
![unnamed 1](https://user-images.githubusercontent.com/24428333/51463420-77c6dd00-1d63-11e9-8c62-0c00643f4999.png)

**Comment by Jeje2201** [comment]
**Problème fixé** https://github.com/Jeje2201/ScrumManager/commit/dcb6d1b1070e946e5c36ec3edccca0296148f8ea
- Simple ajout d'un colspan au lieu d'essayer de dupliquer le td autant que possible.
- Colspan mit à 10 pour être sûr que dans tous les cas il fit toutes les colonnes

Passé de 
```html
<td align="center">0 donnée</td>
html <td align="center">0 donnée</td>
html <td align="center">0 donnée</td>
```
en
``` html
<td align="center" colspan="10">0 donnée</td>
```
