### ISSUE TITLE
Pas de jus on sait pas

### ISSUE THREAD

**Issue by FredericBerton** [Jeje2201/ScrumManager#26]
Si j'ai une perte de connexion internet on n'est pas prévenu, on remplit les fiches de temps mais rien ne s'enregistre en fait. C'est frustrant, mais mineur. Gros poutou

**Comment by Jeje2201** [comment]
Yo, je suis en train de déployer sur toutes les requêtes l'envois d'erreur 50x lorsque la requête rencontre une erreur ne parvient pas à ces fins !
La fix arrivera, j'ai envie de dire très prochainement, mais avec le confinement et les heures attribuées sur les autres projet, va falloir être patient

**Comment by Jeje2201** [comment]
Problème fixé dans ce commit : https://github.com/Jeje2201/ScrumManager/commit/175d85515e56aa070cf8b00e3eaa9dc617a9c539
Arrivera dans la prochaine version !
Exemple : 
![image](https://user-images.githubusercontent.com/19387127/81402213-437e5800-9131-11ea-9def-fbf33edca384.png)
