### ISSUE TITLE
Impossible de descendre tâche supprimée dans PT

### ISSUE THREAD

**Issue by LudovicKosthowa** [Jeje2201/ScrumManager#27]
Ceci est un bug / ajout de fonctionnalité:
J'ai voulu descendre une tâche (supprimée dans PT) pour l'enlever de mes "choses à faire" et j'ai un cette erreur dans la console:
![image](https://user-images.githubusercontent.com/50136487/80946644-cda38500-8dee-11ea-89c9-cba82d2a5138.png)

Du coup, est-il possible d'avoir soit un bouton "supprimer tâche" dans scrummannager ou un système qui supprime les tâches de scrum si elles sont supprimées dans PT aussi ?
ou alors au moins un petit message d'erreur qui catch le retour 400 ? 

Voila merci :)

**Comment by Jeje2201** [comment]
Bien vu ! Le cas n'était jamais apparu ! Le catch de l'erreur 400 a été rajouté dans ce commit : https://github.com/Jeje2201/ScrumManager/commit/27413b30ed905c82747aaccb6c7db35b6c912b7d  

Maintenant à voir avec Fred pour savoir si on laisse les utilisateurs supprimer leurs taches eux même ou non ou si lorsqu'on tombe sur l'erreur 404 on la supprimerais pas auto effectivement ! 


Je lui envois l'issue par mail pour qu'il vienne partager son avis

**Comment by Jeje2201** [comment]
Réponse de Fred :

> Beh oui on peut leur laisser le droit...

Donc ça arrive dans la prochaine mise à jour 👍

**Comment by Jeje2201** [comment]
Fonctionnalité codé https://github.com/Jeje2201/ScrumManager/commit/8f4f55ce6ce16d8f87cf92c099a6fe69eca73dda

Arrive automatiquement comme prévu dans la futur mise à jour
