### ISSUE TITLE
Difficulté à remplir les fiches de temps

### ISSUE THREAD

**Issue by Angelique-NS** [Jeje2201/ScrumManager#33]
Je suis sur Microsoft Edge, et quand je remplis mes fiches de temps (ex : Je selectionne "Reneco Apps" je met "50%" je clique sur "Envoyer" ) rien ne se passe visuellement, donc je ne sais pas si ce que je viens d'envoyer est prit en compte
Finalement en rafraichissant ou en passant d'une date à une autre je peux voir que ma fiche de temps a été complétée mais bon, ça ressemble bien à un bug !

**Comment by Jeje2201** [comment]
Effectivement, j'arrive à reproduire le bug, merci pour toutes ces infos, je fix ça aujourd'hui et je met à jour l'application directement après

**Comment by Jeje2201** [comment]
Fixé et en prod, commit en question : https://github.com/Jeje2201/ScrumManager/commit/80e06db9cb6f47f30cb2483de82887cb6e64694c
