### ISSUE TITLE
URGENT : ajout d'un filtre ds tps passé par une ressource

### ISSUE THREAD

**Issue by FredericBerton** [Jeje2201/ScrumManager#38]
comme tu préfères, un user "all" ou une checkbox a coté de la liste genre "[] all" dans tous les cas la requete devient plus la meme parcequ'on perd le "where user..." quand c'est du all donc y'aura les deux requete dans le code et le choix de detecter laquelle utiliser donc les deux sont pareil a rajouté

Il faut une série de checkbox pour les users et une pour les projets.
Merci

**Comment by Jeje2201** [comment]
Merci de passer par l'application scrum manager pour auto appliquer un label sinon elle n’apparaît pas dans ma liste.

Normalement ceci a été appliqué après avoir vu avec Noémie pour la nouvelle table
