### ISSUE TITLE
Champ de nombre d'heure réelle pré-rempli

### ISSUE THREAD

**Issue by Angelique-NS** [Jeje2201/ScrumManager#47]
Quand on s'apprête à valider une tâche, ce serai cool d'avoir par défaut le nombre d'heure indiqué initialement dans la pop-up, après libre à l'utilisateur de réajuster, mais ça évite de réécrire le nombre à chaque fois :)
![image](https://user-images.githubusercontent.com/60650473/88662018-adc3ea80-d0d9-11ea-8a5b-7c5d84de33fa.png)

**Comment by anthonyHenryNS** [comment]
+1 :P

**Comment by Jeje2201** [comment]
Rien que parceque c'est validé par quelqu'un d'autre, c'est ajouté !
Merci pour l'idée, ce type d'issue est un vrai plaisir, c'est clair, screenshot, participation, je vous aime
Merci @anthonyHenryNS @Angelique-NS 
Commit envoyé en dev, prochaine maj prend le changement
