### ISSUE TITLE
Erreur "Pas d'objectifs vide" à l'attribution d'un objectif

### ISSUE THREAD

**Issue by anthonyHenryNS** [Jeje2201/ScrumManager#48]
Erreur "Pas d'objectifs vide" lorsque je m'attribue un objectif alors que le j'ai bien tout set correctement.
![erreur_objectif](https://user-images.githubusercontent.com/58810894/88790578-aadbff00-d198-11ea-967d-d1fb91ff1bcc.png)

**Comment by Jeje2201** [comment]
Merci pour le report ❤️ 
Problème fixé et envoyé en prod
