### ISSUE TITLE
Auto validation d'une tâche importé depuis Pivotal si elle est validé sur ce dernier

### ISSUE THREAD

**Issue by anthonyHenryNS** [Jeje2201/ScrumManager#49]
Lorsque l'ont planifie une tâche depuis Pivotal qui est déjà validé sur ce dernier, elle est auto validé sur SM ce qui empêche de set le nombre d'heures réelles qu'on y a passé comme on peut le faire à la validation manuel.

Solution : ne pas auto valider la tâche et laisser l'utilisateur le faire à la main.

**Comment by Jeje2201** [comment]
fixé dans le prochain commit en master
