### ISSUE TITLE
Une notification lorsqu'on valide un tâche

### ISSUE THREAD

**Issue by LudovicKosthowa** [Jeje2201/ScrumManager#8]
Ajouter une notification lorsqu'on valide un tâche
Merci bro !

**Comment by Jeje2201** [comment]
Effectivement, c'était parti pour ne laisser place qu'aux erreurs si trop de tâches push d'un coup, c'est à nouveau présent dans le commit suivant : https://github.com/Jeje2201/ScrumManager/commit/dbf8dd7996b898b8c49bab6de5f1b9e156a093f0
Rajouté dans la prochaine mise à jour 👍
