### ISSUE TITLE
Un nombre anormal de fiche de temps non remplies

### ISSUE THREAD

**Issue by LudovicKosthowa** [Jeje2201/ScrumManager#9]
Bonjour Monsieur le développeur,

J'ai 2 fiches de temps à remplir (pas bien !!)
mais elles ne s'affichent pas dans le graphique 

Merci de résoudre ce problème d'affichage Ô grand maître scrum

![image](https://user-images.githubusercontent.com/50136487/74428340-1afc0000-4e59-11ea-910e-12af8ce838b4.png)

**Comment by LudovicKosthowa** [comment]
De plus, sur le over des fiches de temps (barres rouges) il y a 12800 fiches de temps à remplir: soit les personnes concernées non pas fait de fiches de temps depuis 35 ans (sachant que NS a été créé en 2008-2009 ;) )

**Comment by Jeje2201** [comment]
Effectivement 2 problèmes 

- Certains users avaient trop de fiches de temps  

Ce problème est apparu suite à la dernière mise à jour, en changeant les informations de certains users, leur date d'arrivée dans la boite à totalement sauté, l'input date ne recevait pas le bon format et set automatiquement la date en 01/01/1970 ce qui, effectivement comme tes calculs le montre, représente cette idée des 35ans ~, fixé avec le commit suivant : https://github.com/Jeje2201/ScrumManager/commit/b13f9fbcfc825506256f746a74ef9fc1fa93287a

- Certains users avaient un nombre négatif de fiches de temps

Ce problème venait du fait que les users remplissaient leur fiches de temps en avance lorsqu'ils partent à l'école pour 2 semaines ou autre raison. La requête compare maintenant avec la date d'aujourd'hui au maximum, plus possible d'avoir un nombre négatif, fixé avec le commit suivant : https://github.com/Jeje2201/ScrumManager/commit/165d1b3d982aa370969aa2dbf6f92144f2cd4ba9

Le tout sera implémenté dans la prochaine maj, le problème n'interfère pas avec l'ajout ou la suppression de fiche de temps donc pas besoin de push de suite 👍
